public enum TypeModel {
    TOYOTA_CAMRY_30SE, TOYOTA_CAMRY_30XLE, TOYOTA_CAMRY_30LE, TOYOTA_CAMRY_30XSE,
    TOYOTA_CAMRY_40SE, TOYOTA_CAMRY_40XLE, TOYOTA_CAMRY_40LE, TOYOTA_CAMRY_40XSE,
    TOYOTA_CAMRY_50SE, TOYOTA_CAMRY_50XLE, TOYOTA_CAMRY_50LE, TOYOTA_CAMRY_50XSE

}
